---
- name: Setup Kubernetes environment on Ubuntu
  hosts: all
  become: true
  tasks:
    - name: Disable swap
      command: swapoff -a

    - name: Remove swap entry from fstab
      mount:
        name: none
        fstype: swap
        state: absent

    - name: Load necessary kernel modules
      copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter

    - name: Load overlay module
      modprobe:
        name: overlay
        state: present

    - name: Load br_netfilter module
      modprobe:
        name: br_netfilter
        state: present

    - name: Set sysctl parameters
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1

    - name: Apply sysctl parameters
      command: sysctl --system

    - name: Install containerd
      apt:
        name: containerd
        state: present
        update_cache: yes

    - name: Create containerd configuration file
      command: mkdir -p /etc/containerd

    - name: Generate default containerd configuration
      command: containerd config default
      register: containerd_default_config

    - name: Save default containerd configuration
      copy:
        dest: /etc/containerd/config.toml
        content: "{{ containerd_default_config.stdout }}"

    - name: Set SystemdCgroup to true in containerd configuration
      replace:
        path: /etc/containerd/config.toml
        regexp: 'SystemdCgroup = false'
        replace: 'SystemdCgroup = true'

    - name: Restart containerd
      systemd:
        name: containerd
        state: restarted

    - name: Install dependencies for Kubernetes
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg

    - name: Add Kubernetes GPG key
      apt_key:
        url: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
        state: present
        keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Add Kubernetes repository
      apt_repository:
        repo: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /'
        state: present
        filename: kubernetes

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Kubernetes packages
      apt:
        name:
          - kubelet=1.29.1-1.1
          - kubeadm=1.29.1-1.1
          - kubectl=1.29.1-1.1
        state: present

    - name: Hold kubelet package
      shell: apt-mark hold kubelet

    - name: Hold kubeadm package
      shell: apt-mark hold kubeadm

    - name: Hold kubectl package
      shell: apt-mark hold kubectl

    - name: Hold containerd package
      shell: apt-mark hold containerd

    - name: Ensure kubelet service is running
      systemd:
        name: kubelet
        state: started
        enabled: yes

    - name: Ensure containerd service is running
      systemd:
        name: containerd
        state: started
        enabled: yes
