---
- name: Configure worker node for Kubernetes
  hosts: all
  become: yes

  tasks:
    - name: Disable swap
      command: swapoff -a

    - name: Load necessary kernel modules
      copy:
        content: |
          overlay
          br_netfilter
        dest: /etc/modules-load.d/k8s.conf

    - name: Load overlay module
      modprobe:
        name: overlay

    - name: Load br_netfilter module
      modprobe:
        name: br_netfilter

    - name: Ensure sysctl params are set
      copy:
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1
        dest: /etc/sysctl.d/k8s.conf

    - name: Apply sysctl params without reboot
      command: sysctl --system

    - name: Install containerd
      apt:
        name: containerd
        state: present
        update_cache: yes

    - name: Create containerd configuration directory
      file:
        path: /etc/containerd
        state: directory

    - name: Generate default containerd config
      command: containerd config default
      register: containerd_config

    - name: Write containerd config to file
      copy:
        content: "{{ containerd_config.stdout }}"
        dest: /etc/containerd/config.toml

    - name: Set SystemdCgroup to true
      replace:
        path: /etc/containerd/config.toml
        regexp: '(\s*SystemdCgroup\s*=\s*)false'
        replace: '\1true'

    - name: Restart containerd
      service:
        name: containerd
        state: restarted

    - name: Install dependencies for Kubernetes packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gpg

    - name: Add Google's apt repository gpg key
      command: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Add the Kubernetes apt repository
      copy:
        content: |
          deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /
        dest: /etc/apt/sources.list.d/kubernetes.list

    - name: Update apt package list
      apt:
        update_cache: yes

    - name: Install Kubernetes packages
      apt:
        name:
          - kubelet=1.29.1-1.1
          - kubeadm=1.29.1-1.1
          - kubectl=1.29.1-1.1
        state: present

    - name: Hold kubelet package
      shell: apt-mark hold kubelet

    - name: Hold kubeadm package
      shell: apt-mark hold kubeadm

    - name: Hold kubectl package
      shell: apt-mark hold kubectl

    - name: Hold containerd package
      shell: apt-mark hold containerd
