---
- name: Set up Kubernetes Master with Calico Networking
  hosts: all
  vars:
    ansible_user: "osboxes"
    default_gateway: "192.168.56.12"
  become: true
  tasks:
    - name: Ensure required directories exist
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - "$HOME/.kube"

    - name: Initialize Kubernetes cluster
      command: kubeadm init --kubernetes-version v1.29.1 --apiserver-advertise-address={{default_gateway}} --pod-network-cidr=10.10.0.0/16 --control-plane-endpoint=master.kubernetes.cluster

    - name: Create a .kube directory for user
      file:
        path: /home/{{ ansible_user }}/.kube
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Copy kubeconfig to user directory
      command: sudo cp -i /etc/kubernetes/admin.conf /home/{{ ansible_user }}/.kube/config
      become: true

    - name: Change ownership of kubeconfig
      command: sudo chown {{ ansible_user }}:{{ ansible_user }} /home/{{ ansible_user }}/.kube/config
      become: true
    
    # - name: Download Calico YAML
    #   get_url:
    #     url: https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/calico.yaml
    #     dest: /home/{{ ansible_user }}/calico.yaml
    #   become: false

    # - name: Apply Calico network
    #   command: kubectl apply -f /home/{{ ansible_user }}/calico.yaml
    #   become: false
